### ISSUE TITLE
Sync failing - Process completed with exit code 1.

### ISSUE THREAD

**Issue by bvendsel** [e-alizadeh/Zotero2Readwise#43]
<img width="1088" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/1540392/232119499-9f00fcc3-7d45-4248-9155-5c087718045b.png">

**Comment by bvendsel** [comment]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/1540392/232119706-2b9c8b32-5356-4948-8948-2368f60a541c.png">

**Comment by e-alizadeh** [comment]
@bvendsel Can you run follow instructions on running the script through a Python terminal as shown [here](https://github.com/e-alizadeh/Zotero2Readwise#approach-2-through-python-terminal) to generate a local json file of highlights that were failed. You can check the highlights to see if there is anything strange.

Based on the error code (400 bad request), It seems to me that there are some highlights that might break the Readwise restrictions. For instance, Readwise sets limits to the number of characters per highlight.

**Comment by bvendsel** [comment]
@e-alizadeh I did what you asked and got an empty json file back. I'm fairly certain it isn't a highlight as i recently archived off my old library and started fresh as part of a new job. Unless that could have caused a problem?

**Comment by e-alizadeh** [comment]
@bvendsel Based on your description, there seems to be something wrong with your new setup, because I haven't updated the library, nor I see a Readwise API change that may impact the library. 
Just a curiosity question, is there by any chance a change in the following items that are used as environment variables?
- Readwise access token
- Zotero API key
- Zotero personal or group ID

**Comment by bvendsel** [comment]
There shouldn't be but there is always a chance. Thanks for your help. I'll
just clear everything out and start again. Too useful not to have working
:)

**Comment by alibrack** [comment]
Hi, I'm having this same issue, but with this json file generated for failed items. It seems to be an issue with the author field? 

(json file changed to txt just to be able to upload)
[error_log_400_failed_post_request_to_readwise.txt](https://github.com/e-alizadeh/Zotero2Readwise/files/12602135/error_log_400_failed_post_request_to_readwise.txt)

**Comment by e-alizadeh** [comment]
@alibrack I got a chance to look at this. The issue comes from the fact that I only export Responses from Readwise (https://github.com/e-alizadeh/Zotero2Readwise/blob/142f8eb417da9e365d20ad391b25a3362b932f61/zotero2readwise/readwise.py#L71).

If you still have the issue I can update the code to export the error along with the highlight itself?

**Comment by alibrack** [comment]
That would be really helpful! I am still having the issue, yes. On Sep 24, 2023, at 1:04 PM, Essi Alizadeh ***@***.***> wrote:﻿
@alibrack I got a chance to look at this. The issue comes from the fact that I only export Responses from Readwise (https://github.com/e-alizadeh/Zotero2Readwise/blob/142f8eb417da9e365d20ad391b25a3362b932f61/zotero2readwise/readwise.py#L71).
If you still have the issue I can update the code to export the error along with the highlight itself?

**Comment by ncarboni** [comment]
I am also affected by this problem. I am currently using Zotero2Readwise-Sync and in the Zotero to Readwise Automation phase I get the error "TypeError: unsupported operand type(s) for |: 'dict' and 'dict'"
Here's the log:

```python
Run python run.py *** *** ***
  python run.py *** *** ***
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python[2](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:3).8.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x6[4](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
Retrieving ALL annotations from Zotero Database
It may take some time...
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    zt2rw.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zotero2readwise/zt2rw.py", line [5](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:5)3, in run
    zot_annots_notes = self.get_all_zotero_items()
  File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:6)4/lib/python3.8/site-packages/zotero2readwise/zt2rw.py", line 42, in get_all_zotero_items
    items.extend(self.retrieve_all("annotation", self.since))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/zotero2readwise/zt2rw.py", line 82, in retrieve_all
    query = self.zotero_client.items(itemType={item_type}, since=since)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 16[7](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:7), in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/ncarboni/Zotero2Readwise-Sync/actions/runs/12625808503/job/35178035782#step:6:8).18/x64/lib/python3.8/site-packages/pyzotero/zotero.py", line 460, in _retrieve_data
    merged_params = params | self.url_params
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
Error: Process completed with exit code 1.
```

To debug it, if I try, on my machine to run:
```python
zt_rw = Zotero2Readwise(
    readwise_token="readwise_api",  # Visit https://readwise.io/access_token)
    zotero_key="zotero_key_just_for_this_process",  # Visit https://www.zotero.org/settings/keys
    zotero_library_id="my_user_id_for_api_call", # Visit https://www.zotero.org/settings/keys
    zotero_library_type="user", # "user" (default) or "group"
    include_annotations=True, # Include Zotero annotations -> Default: True
    include_notes=False, # Include Zotero notes -> Default: False
)
zt_rw.run()
```
I get an entirely new problem:

```
---------------------------------------------------------------------------
HTTPStatusError                           Traceback (most recent call last)
File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/pyzotero/zotero.py:490, in Zotero._retrieve_data(self, request, params)
    489 try:
--> 490     self.request.raise_for_status()
    491 except httpx.HTTPError as exc:

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/httpx/_models.py:829, in Response.raise_for_status(self)
    828 message = message.format(self, error_type=error_type)
--> 829 raise HTTPStatusError(message, request=request, response=self)

HTTPStatusError: Client error '400 Bad Request' for url 'https://api.zotero.org/users/my_user_id_for_api_call/items?locale=en-US&itemType=%7B%27annotation%27%7D&since=0&format=json&limit=100'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

The above exception was the direct cause of the following exception:

UnsupportedParams                         Traceback (most recent call last)
Cell In[9], line 9
      1 zt_rw = Zotero2Readwise(
      2     readwise_token="readwise_api",  # Visit https://readwise.io/access_token)
      3     zotero_key="zotero_key_just_for_this_process",  # Visit https://www.zotero.org/settings/keys
   (...)
      7     include_notes=False, # Include Zotero notes -> Default: False
      8 )
----> 9 zt_rw.run()

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/zotero2readwise/zt2rw.py:53, in Zotero2Readwise.run(self, zot_annots_notes)
     51 def run(self, zot_annots_notes: List[Dict] = None) -> None:
     52     if zot_annots_notes is None:
---> 53         zot_annots_notes = self.get_all_zotero_items()
     55     formatted_items = self.zotero.format_items(zot_annots_notes)
     57     if self.zotero.failed_items:

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/zotero2readwise/zt2rw.py:42, in Zotero2Readwise.get_all_zotero_items(self)
     40 items = []
     41 if self.include_annots:
---> 42     items.extend(self.retrieve_all("annotation", self.since))
     44 if self.include_notes:
     45     items.extend(self.retrieve_all("note", self.since))

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/zotero2readwise/zt2rw.py:82, in Zotero2Readwise.retrieve_all(self, item_type, since)
     79     print(f"Retrieving {item_type}s since last run from Zotero Database")
     81 print("It may take some time...")
---> 82 query = self.zotero_client.items(itemType={item_type}, since=since)
     83 return self.zotero_client.everything(query)

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/pyzotero/zotero.py:184, in retrieve.<locals>.wrapped_f(self, *args, **kwargs)
    182 if kwargs:
    183     self.add_parameters(**kwargs)
--> 184 retrieved = self._retrieve_data(func(self, *args))
    185 # we now always have links in the header response
    186 self.links = self._extract_links()

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/pyzotero/zotero.py:492, in Zotero._retrieve_data(self, request, params)
    490     self.request.raise_for_status()
    491 except httpx.HTTPError as exc:
--> 492     error_handler(self, self.request, exc)
    493 backoff = self.request.headers.get("backoff") or self.request.headers.get(
    494     "retry-after"
    495 )
    496 if backoff:

File /opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.12/site-packages/pyzotero/zotero.py:1701, in error_handler(zot, req, exc)
   1699             raise error_codes.get(req.status_code)(err_msg(req))
   1700         else:
-> 1701             raise error_codes.get(req.status_code)(err_msg(req)) from exc
   1702 else:
   1703     if not exc:

UnsupportedParams: 
Code: 400
URL: https://api.zotero.org/users/my_user_id_for_api_call/items?locale=en-US&itemType=%7B%27annotation%27%7D&since=0&format=json&limit=100
Method: GET
Response: Invalid itemType '{'annotation'}'
```

any idea how to debug it?
